const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //admin
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_CITY_START: "FETCH_CITY_START",
  FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
  FETCH_CITY_FAILED: "FETCH_CITY_FAILED",

  CREATE_SEEKER_SUCCESS: "CREATE_SEEKER_SUCCESS",
  CREATE_SEEKER_FAILED: "CREATE_SEEKER_FAILED",

  DELETE_SEEKER_SUCCESS: "DELETE_SEEKER_SUCCESS",
  DELETE_SEEKER_FAILED: "DELETE_SEEKER_FAILED",

  EDIT_SEEKER_SUCCESS: "EDIT_SEEKER_SUCCESS",
  EDIT_SEEKER_FAILED: "EDIT_SEEKER_FAILED",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",
});

export default actionTypes;
