const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //admin
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  FETCH_CITY_START: "FETCH_CITY_START",
  FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
  FETCH_CITY_FAILED: "FETCH_CITY_FAILED",

  CREATE_Users_SUCCESS: "CREATE_Users_SUCCESS",
  CREATE_Users_FAILED: "CREATE_Users_FAILED",

  DELETE_Users_SUCCESS: "DELETE_Users_SUCCESS",
  DELETE_Users_FAILED: "DELETE_Users_FAILED",

  EDIT_Users_SUCCESS: "EDIT_Users_SUCCESS",
  EDIT_Users_FAILED: "EDIT_Users_FAILED",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

  FETCH_ALL_SEEKER_SUCCESS: "FETCH_ALL_SEEKER_SUCCESS",
  FETCH_ALL_SEEKER_FAILED: "FETCH_ALL_SEEKER_FAILED",

  FETCH_TOP_COMPANY_SUCCESS: "FETCH_TOP_COMPANY_SUCCESS",
  FETCH_TOP_COMPANY_FAILED: "FETCH_TOP_COMPANY_FAILED",

  FETCH_ALL_COMPANYS_SUCCESS: "FETCH_ALL_COMPANYS_SUCCESS",
  FETCH_ALL_COMPANYS_FAILED: "FETCH_ALL_COMPANYS_FAILED",

  SAVE_DETAIL_CONPANY_SUCCESS: "SAVE_DETAIL_CONPANY_SUCCESS",
  SAVE_DETAIL_CONPANY_FAILED: "SAVE_DETAIL_CONPANY_FAILED",

  SAVE_INFOR_RECRUIT_SUCCESS: "SAVE_INFOR_RECRUIT_SUCCESS",
  SAVE_INFOR_RECRUIT_FAILED: "SAVE_INFOR_RECRUIT_FAILED",

  FETCH_ALL_POST_SUCCESS: "FETCH_ALL_POST_SUCCESS",
  FETCH_ALL_POST_FAILED: "FETCH_ALL_POST_FAILED",
});

export default actionTypes;
